//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    
    public partial class pa_file_ObtieneReglasArchivoPorLinea_Result
    {
        public int IdReglaArchivo { get; set; }
        public string InformacionCampo { get; set; }
        public Nullable<int> CaracterInicial { get; set; }
        public Nullable<int> LargoCampo { get; set; }
        public string TipoCampo { get; set; }
        public string TipoValidacion { get; set; }
        public string ReglaValidacion { get; set; }
        public string TablaDestino { get; set; }
    }
}
