//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoArchivo
    {
        public EstadoArchivo()
        {
            this.Archivoes = new HashSet<Archivo>();
        }
    
        public int EstadoArchivoId { get; set; }
        public string NombreEstado { get; set; }
    
        public virtual ICollection<Archivo> Archivoes { get; set; }
    }
}
