//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public Documento()
        {
            this.Checkeados = new HashSet<Checkeado>();
            this.DocumentoSolicitados = new HashSet<DocumentoSolicitado>();
        }
    
        public int DocumentoId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Checkeado> Checkeados { get; set; }
        public virtual ICollection<DocumentoSolicitado> DocumentoSolicitados { get; set; }
    }
}
