//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSV
    {
        public int CSVId { get; set; }
        public string Abreviatura { get; set; }
        public string Descripcion { get; set; }
        public bool VidaCamara { get; set; }
        public string CodigoDIS { get; set; }
    }
}
