//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DISEntities : DbContext
    {
        public DISEntities()
            : base("name=DISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exactu> Exactus { get; set; }
        public virtual DbSet<HistorialCargaArchivo> HistorialCargaArchivos { get; set; }
        public virtual DbSet<ReglaArchivo> ReglaArchivos { get; set; }
        public virtual DbSet<AFP> AFPs { get; set; }
        public virtual DbSet<Archivo> Archivos { get; set; }
        public virtual DbSet<Bitacora> Bitacoras { get; set; }
        public virtual DbSet<Checkeado> Checkeados { get; set; }
        public virtual DbSet<ContratoCSV> ContratoCSVs { get; set; }
        public virtual DbSet<Contrato> Contratos { get; set; }
        public virtual DbSet<Correlativo> Correlativos { get; set; }
        public virtual DbSet<CSV> CSVs { get; set; }
        public virtual DbSet<Documento> Documentos { get; set; }
        public virtual DbSet<DocumentoSolicitado> DocumentoSolicitados { get; set; }
        public virtual DbSet<EstadoArchivo> EstadoArchivos { get; set; }
        public virtual DbSet<EstadoPago> EstadoPagos { get; set; }
        public virtual DbSet<Imputacion> Imputacions { get; set; }
        public virtual DbSet<Moneda> Monedas { get; set; }
        public virtual DbSet<MontoAlto> MontoAltos { get; set; }
        public virtual DbSet<Pago> Pagos { get; set; }
        public virtual DbSet<Parametro> Parametros { get; set; }
        public virtual DbSet<Parentesco> Parentescos { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<RegistroMontoAlto> RegistroMontoAltos { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Siniestro> Siniestros { get; set; }
        public virtual DbSet<TipoArchivo> TipoArchivos { get; set; }
        public virtual DbSet<TipoCambio> TipoCambios { get; set; }
        public virtual DbSet<TipoDocumentoIdentificacion> TipoDocumentoIdentificacions { get; set; }
        public virtual DbSet<TipoInforme> TipoInformes { get; set; }
        public virtual DbSet<TipoMoneda> TipoMonedas { get; set; }
        public virtual DbSet<TipoMovimiento> TipoMovimientos { get; set; }
        public virtual DbSet<TipoPension> TipoPensions { get; set; }
        public virtual DbSet<TipoRegistro> TipoRegistros { get; set; }
        public virtual DbSet<TipoSolicitude> TipoSolicitudes { get; set; }
        public virtual DbSet<Consulta> Consultas { get; set; }
        public virtual DbSet<CheckList> CheckLists { get; set; }
    
        public virtual int pa_audit_InsertaBitacora(Nullable<int> param_IdUsuario, string param_Descripcion, string param_Comando, Nullable<int> param_Idarchivo)
        {
            var param_IdUsuarioParameter = param_IdUsuario.HasValue ?
                new ObjectParameter("Param_IdUsuario", param_IdUsuario) :
                new ObjectParameter("Param_IdUsuario", typeof(int));
    
            var param_DescripcionParameter = param_Descripcion != null ?
                new ObjectParameter("Param_Descripcion", param_Descripcion) :
                new ObjectParameter("Param_Descripcion", typeof(string));
    
            var param_ComandoParameter = param_Comando != null ?
                new ObjectParameter("Param_Comando", param_Comando) :
                new ObjectParameter("Param_Comando", typeof(string));
    
            var param_IdarchivoParameter = param_Idarchivo.HasValue ?
                new ObjectParameter("Param_Idarchivo", param_Idarchivo) :
                new ObjectParameter("Param_Idarchivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_audit_InsertaBitacora", param_IdUsuarioParameter, param_DescripcionParameter, param_ComandoParameter, param_IdarchivoParameter);
        }
    
        public virtual ObjectResult<pa_devuelveresultado_Result> pa_devuelveresultado(Nullable<int> idarchivo)
        {
            var idarchivoParameter = idarchivo.HasValue ?
                new ObjectParameter("idarchivo", idarchivo) :
                new ObjectParameter("idarchivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_devuelveresultado_Result>("pa_devuelveresultado", idarchivoParameter);
        }
    
        public virtual int pa_envioCorreo_Procesos(string para, string cC, string cCO, string asunto, string cuerpo, string formatoCuerpo, string archivos)
        {
            var paraParameter = para != null ?
                new ObjectParameter("Para", para) :
                new ObjectParameter("Para", typeof(string));
    
            var cCParameter = cC != null ?
                new ObjectParameter("CC", cC) :
                new ObjectParameter("CC", typeof(string));
    
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var asuntoParameter = asunto != null ?
                new ObjectParameter("Asunto", asunto) :
                new ObjectParameter("Asunto", typeof(string));
    
            var cuerpoParameter = cuerpo != null ?
                new ObjectParameter("Cuerpo", cuerpo) :
                new ObjectParameter("Cuerpo", typeof(string));
    
            var formatoCuerpoParameter = formatoCuerpo != null ?
                new ObjectParameter("FormatoCuerpo", formatoCuerpo) :
                new ObjectParameter("FormatoCuerpo", typeof(string));
    
            var archivosParameter = archivos != null ?
                new ObjectParameter("Archivos", archivos) :
                new ObjectParameter("Archivos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_envioCorreo_Procesos", paraParameter, cCParameter, cCOParameter, asuntoParameter, cuerpoParameter, formatoCuerpoParameter, archivosParameter);
        }
    
        public virtual int pa_file_AgregaReferenciaTablaArchivo(string nombreArchivo)
        {
            var nombreArchivoParameter = nombreArchivo != null ?
                new ObjectParameter("NombreArchivo", nombreArchivo) :
                new ObjectParameter("NombreArchivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_file_AgregaReferenciaTablaArchivo", nombreArchivoParameter);
        }
    
        public virtual int pa_file_ArchivoValido(Nullable<int> idArchivo)
        {
            var idArchivoParameter = idArchivo.HasValue ?
                new ObjectParameter("IdArchivo", idArchivo) :
                new ObjectParameter("IdArchivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_file_ArchivoValido", idArchivoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_file_CantidadRegistroArchivo(Nullable<int> idArchivo)
        {
            var idArchivoParameter = idArchivo.HasValue ?
                new ObjectParameter("IdArchivo", idArchivo) :
                new ObjectParameter("IdArchivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_file_CantidadRegistroArchivo", idArchivoParameter);
        }
    
        public virtual int pa_file_CierreCarga(Nullable<int> idCarga)
        {
            var idCargaParameter = idCarga.HasValue ?
                new ObjectParameter("IdCarga", idCarga) :
                new ObjectParameter("IdCarga", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_file_CierreCarga", idCargaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_file_ConsultaEstadoArchivo(string nombreArchivo)
        {
            var nombreArchivoParameter = nombreArchivo != null ?
                new ObjectParameter("NombreArchivo", nombreArchivo) :
                new ObjectParameter("NombreArchivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_file_ConsultaEstadoArchivo", nombreArchivoParameter);
        }
    
        public virtual int pa_file_Imputa_Nomina(Nullable<int> idarchivo, Nullable<int> idusuario)
        {
            var idarchivoParameter = idarchivo.HasValue ?
                new ObjectParameter("idarchivo", idarchivo) :
                new ObjectParameter("idarchivo", typeof(int));
    
            var idusuarioParameter = idusuario.HasValue ?
                new ObjectParameter("idusuario", idusuario) :
                new ObjectParameter("idusuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_file_Imputa_Nomina", idarchivoParameter, idusuarioParameter);
        }
    
        public virtual int pa_file_InsertaHistorialCarga(Nullable<int> aux_IdArchivo, Nullable<int> aux_IdReglaArchivo, string aux_TipoLinea, Nullable<int> aux_NumeroLinea, Nullable<int> aux_CampoInicial, Nullable<int> aux_LargoCampo, string aux_ValorCampo, Nullable<int> aux_CumpleValidacion)
        {
            var aux_IdArchivoParameter = aux_IdArchivo.HasValue ?
                new ObjectParameter("Aux_IdArchivo", aux_IdArchivo) :
                new ObjectParameter("Aux_IdArchivo", typeof(int));
    
            var aux_IdReglaArchivoParameter = aux_IdReglaArchivo.HasValue ?
                new ObjectParameter("Aux_IdReglaArchivo", aux_IdReglaArchivo) :
                new ObjectParameter("Aux_IdReglaArchivo", typeof(int));
    


            var aux_TipoLineaParameter = aux_TipoLinea != null ?
                new ObjectParameter("Aux_TipoLinea", aux_TipoLinea) :
                new ObjectParameter("Aux_TipoLinea", typeof(string));
    
            var aux_NumeroLineaParameter = aux_NumeroLinea.HasValue ?
                new ObjectParameter("Aux_NumeroLinea", aux_NumeroLinea) :
                new ObjectParameter("Aux_NumeroLinea", typeof(int));
    
            var aux_CampoInicialParameter = aux_CampoInicial.HasValue ?
                new ObjectParameter("Aux_CampoInicial", aux_CampoInicial) :
                new ObjectParameter("Aux_CampoInicial", typeof(int));
    
            var aux_LargoCampoParameter = aux_LargoCampo.HasValue ?
                new ObjectParameter("Aux_LargoCampo", aux_LargoCampo) :
                new ObjectParameter("Aux_LargoCampo", typeof(int));
    
            var aux_ValorCampoParameter = aux_ValorCampo != null ?
                new ObjectParameter("Aux_ValorCampo", aux_ValorCampo) :
                new ObjectParameter("Aux_ValorCampo", typeof(string));
    
            var aux_CumpleValidacionParameter = aux_CumpleValidacion.HasValue ?
                new ObjectParameter("Aux_CumpleValidacion", aux_CumpleValidacion) :
                new ObjectParameter("Aux_CumpleValidacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_file_InsertaHistorialCarga", aux_IdArchivoParameter, aux_IdReglaArchivoParameter, aux_TipoLineaParameter, aux_NumeroLineaParameter, aux_CampoInicialParameter, aux_LargoCampoParameter, aux_ValorCampoParameter, aux_CumpleValidacionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_file_InsertaReferenciaArchivo(string nombreArchivo, string usuarioModificacion)
        {
            var nombreArchivoParameter = nombreArchivo != null ?
                new ObjectParameter("NombreArchivo", nombreArchivo) :
                new ObjectParameter("NombreArchivo", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion != null ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_file_InsertaReferenciaArchivo", nombreArchivoParameter, usuarioModificacionParameter);
        }
    
        public virtual ObjectResult<pa_file_ObtieneErrorArchivo_Result> pa_file_ObtieneErrorArchivo(Nullable<int> idArchivo)
        {
            var idArchivoParameter = idArchivo.HasValue ?
                new ObjectParameter("IdArchivo", idArchivo) :
                new ObjectParameter("IdArchivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_file_ObtieneErrorArchivo_Result>("pa_file_ObtieneErrorArchivo", idArchivoParameter);
        }
    
        public virtual ObjectResult<string> pa_file_ObtienePrimerCaracterLineaPorTipoArchivo(string param_TipoArchivo)
        {
            var param_TipoArchivoParameter = param_TipoArchivo != null ?
                new ObjectParameter("Param_TipoArchivo", param_TipoArchivo) :
                new ObjectParameter("Param_TipoArchivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pa_file_ObtienePrimerCaracterLineaPorTipoArchivo", param_TipoArchivoParameter);
        }
    
        public virtual ObjectResult<pa_file_ObtieneReglasArchivoPorLinea_Result> pa_file_ObtieneReglasArchivoPorLinea(string param_TipoArchivo, string param_TipoLinea)
        {
            var param_TipoArchivoParameter = param_TipoArchivo != null ?
                new ObjectParameter("Param_TipoArchivo", param_TipoArchivo) :
                new ObjectParameter("Param_TipoArchivo", typeof(string));
    
            var param_TipoLineaParameter = param_TipoLinea != null ?
                new ObjectParameter("Param_TipoLinea", param_TipoLinea) :
                new ObjectParameter("Param_TipoLinea", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_file_ObtieneReglasArchivoPorLinea_Result>("pa_file_ObtieneReglasArchivoPorLinea", param_TipoArchivoParameter, param_TipoLineaParameter);
        }
    
        public virtual ObjectResult<string> pa_file_ObtieneReglavalidacionArchivo(string archivo, Nullable<int> tipo)
        {
            var archivoParameter = archivo != null ?
                new ObjectParameter("Archivo", archivo) :
                new ObjectParameter("Archivo", typeof(string));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pa_file_ObtieneReglavalidacionArchivo", archivoParameter, tipoParameter);
        }
    
        public virtual ObjectResult<string> pa_file_ObtieneTipoArchivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pa_file_ObtieneTipoArchivos");
        }
    
        public virtual ObjectResult<pa_impactanegocio_Result> pa_impactanegocio(Nullable<int> idarchivo)
        {
            var idarchivoParameter = idarchivo.HasValue ?
                new ObjectParameter("idarchivo", idarchivo) :
                new ObjectParameter("idarchivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_impactanegocio_Result>("pa_impactanegocio", idarchivoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_impactanomina(Nullable<int> idnomina)
        {
            var idnominaParameter = idnomina.HasValue ?
                new ObjectParameter("idnomina", idnomina) :
                new ObjectParameter("idnomina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_impactanomina", idnominaParameter);
        }
    
        public virtual int pa_imputa_aad(Nullable<int> idnomina, Nullable<int> idusuario)
        {
            var idnominaParameter = idnomina.HasValue ?
                new ObjectParameter("idnomina", idnomina) :
                new ObjectParameter("idnomina", typeof(int));
    
            var idusuarioParameter = idusuario.HasValue ?
                new ObjectParameter("idusuario", idusuario) :
                new ObjectParameter("idusuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_imputa_aad", idnominaParameter, idusuarioParameter);
        }
    
        public virtual int pa_imputa_ppp(Nullable<int> idnomina, Nullable<int> idusuario)
        {
            var idnominaParameter = idnomina.HasValue ?
                new ObjectParameter("idnomina", idnomina) :
                new ObjectParameter("idnomina", typeof(int));
    
            var idusuarioParameter = idusuario.HasValue ?
                new ObjectParameter("idusuario", idusuario) :
                new ObjectParameter("idusuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_imputa_ppp", idnominaParameter, idusuarioParameter);
        }
    
        public virtual int pa_imputa_ppr(Nullable<int> idnomina, Nullable<int> idusuario)
        {
            var idnominaParameter = idnomina.HasValue ?
                new ObjectParameter("idnomina", idnomina) :
                new ObjectParameter("idnomina", typeof(int));
    
            var idusuarioParameter = idusuario.HasValue ?
                new ObjectParameter("idusuario", idusuario) :
                new ObjectParameter("idusuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_imputa_ppr", idnominaParameter, idusuarioParameter);
        }
    
        public virtual int pa_imputa_prp(Nullable<int> idnomina, Nullable<int> idusuario)
        {
            var idnominaParameter = idnomina.HasValue ?
                new ObjectParameter("idnomina", idnomina) :
                new ObjectParameter("idnomina", typeof(int));
    
            var idusuarioParameter = idusuario.HasValue ?
                new ObjectParameter("idusuario", idusuario) :
                new ObjectParameter("idusuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_imputa_prp", idnominaParameter, idusuarioParameter);
        }
    
        public virtual int pa_imputa_rgs(Nullable<int> idnomina, Nullable<int> idusuario)
        {
            var idnominaParameter = idnomina.HasValue ?
                new ObjectParameter("idnomina", idnomina) :
                new ObjectParameter("idnomina", typeof(int));
    
            var idusuarioParameter = idusuario.HasValue ?
                new ObjectParameter("idusuario", idusuario) :
                new ObjectParameter("idusuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_imputa_rgs", idnominaParameter, idusuarioParameter);
        }
    
        public virtual ObjectResult<pa_ReporteArchivo_CUSPP_Result> pa_ReporteArchivo_CUSPP(string cUSPP, Nullable<int> archivoId)
        {
            var cUSPPParameter = cUSPP != null ?
                new ObjectParameter("CUSPP", cUSPP) :
                new ObjectParameter("CUSPP", typeof(string));
    
            var archivoIdParameter = archivoId.HasValue ?
                new ObjectParameter("ArchivoId", archivoId) :
                new ObjectParameter("ArchivoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ReporteArchivo_CUSPP_Result>("pa_ReporteArchivo_CUSPP", cUSPPParameter, archivoIdParameter);
        }
    
        public virtual ObjectResult<pa_rpt_archivocarga_fecha_Result> pa_rpt_archivocarga_fecha(Nullable<int> tipo, Nullable<System.DateTime> fechainicio, Nullable<System.DateTime> fechatermino)
        {
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(int));
    
            var fechainicioParameter = fechainicio.HasValue ?
                new ObjectParameter("fechainicio", fechainicio) :
                new ObjectParameter("fechainicio", typeof(System.DateTime));
    
            var fechaterminoParameter = fechatermino.HasValue ?
                new ObjectParameter("fechatermino", fechatermino) :
                new ObjectParameter("fechatermino", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_rpt_archivocarga_fecha_Result>("pa_rpt_archivocarga_fecha", tipoParameter, fechainicioParameter, fechaterminoParameter);
        }
    
        public virtual ObjectResult<pa_rptNominas_Result> pa_rptNominas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_rptNominas_Result>("pa_rptNominas");
        }
    
        public virtual int pa_rptPrimas(string periodo)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_rptPrimas", periodoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_CodigoTransferenciaNomina(string valor, Nullable<int> idArchivo, Nullable<int> largoCampo)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            var idArchivoParameter = idArchivo.HasValue ?
                new ObjectParameter("IdArchivo", idArchivo) :
                new ObjectParameter("IdArchivo", typeof(int));
    
            var largoCampoParameter = largoCampo.HasValue ?
                new ObjectParameter("LargoCampo", largoCampo) :
                new ObjectParameter("LargoCampo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_CodigoTransferenciaNomina", valorParameter, idArchivoParameter, largoCampoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_CUSPP(string valor)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_CUSPP", valorParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_EjecutaProcedimientoAlmacenado(string valor)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_EjecutaProcedimientoAlmacenado", valorParameter);
        }
    
        public virtual ObjectResult<string> pa_valida_EjecutaQuery(string valor)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pa_valida_EjecutaQuery", valorParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_Fecha(string valor, Nullable<System.DateTime> inicio)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Fecha", valorParameter, inicioParameter);
        }
    
        public virtual int pa_valida_MontoAlto(Nullable<int> idarchivo, Nullable<int> idusuario)
        {
            var idarchivoParameter = idarchivo.HasValue ?
                new ObjectParameter("idarchivo", idarchivo) :
                new ObjectParameter("idarchivo", typeof(int));
    
            var idusuarioParameter = idusuario.HasValue ?
                new ObjectParameter("idusuario", idusuario) :
                new ObjectParameter("idusuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_valida_MontoAlto", idarchivoParameter, idusuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_NoEspacios(string valor)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_NoEspacios", valorParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_Numero12x2(string valor)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Numero12x2", valorParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_Numero2x2(string valor)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Numero2x2", valorParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_Numero4x7(string valor)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Numero4x7", valorParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_Numero7x2(string valor)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Numero7x2", valorParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_Numero8x2(string valor)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Numero8x2", valorParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_ObtieneValor(Nullable<int> idArchivo, Nullable<int> numeroLinea, Nullable<int> campoInicial, Nullable<int> largoCampo, string valor)
        {
            var idArchivoParameter = idArchivo.HasValue ?
                new ObjectParameter("IdArchivo", idArchivo) :
                new ObjectParameter("IdArchivo", typeof(int));
    
            var numeroLineaParameter = numeroLinea.HasValue ?
                new ObjectParameter("NumeroLinea", numeroLinea) :
                new ObjectParameter("NumeroLinea", typeof(int));
    
            var campoInicialParameter = campoInicial.HasValue ?
                new ObjectParameter("CampoInicial", campoInicial) :
                new ObjectParameter("CampoInicial", typeof(int));
    
            var largoCampoParameter = largoCampo.HasValue ?
                new ObjectParameter("LargoCampo", largoCampo) :
                new ObjectParameter("LargoCampo", typeof(int));
    
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_ObtieneValor", idArchivoParameter, numeroLineaParameter, campoInicialParameter, largoCampoParameter, valorParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_Periodo(string valor)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Periodo", valorParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_Periodo_PrimaPag(string valor)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_Periodo_PrimaPag", valorParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_persona(string primerNombre, string segundoNombre, string apellidoPaterno, string apellidoMaterno, Nullable<System.DateTime> fechaNacimiento, string cUSPP)
        {
            var primerNombreParameter = primerNombre != null ?
                new ObjectParameter("PrimerNombre", primerNombre) :
                new ObjectParameter("PrimerNombre", typeof(string));
    
            var segundoNombreParameter = segundoNombre != null ?
                new ObjectParameter("SegundoNombre", segundoNombre) :
                new ObjectParameter("SegundoNombre", typeof(string));
    
            var apellidoPaternoParameter = apellidoPaterno != null ?
                new ObjectParameter("ApellidoPaterno", apellidoPaterno) :
                new ObjectParameter("ApellidoPaterno", typeof(string));
    
            var apellidoMaternoParameter = apellidoMaterno != null ?
                new ObjectParameter("ApellidoMaterno", apellidoMaterno) :
                new ObjectParameter("ApellidoMaterno", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var cUSPPParameter = cUSPP != null ?
                new ObjectParameter("CUSPP", cUSPP) :
                new ObjectParameter("CUSPP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_persona", primerNombreParameter, segundoNombreParameter, apellidoPaternoParameter, apellidoMaternoParameter, fechaNacimientoParameter, cUSPPParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_RetornaTrue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_RetornaTrue");
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_SoloNumeros(string valor)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_SoloNumeros", valorParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_SumaDetalleEnTotal(string valor, Nullable<int> idArchivo, Nullable<int> numeroLinea, Nullable<int> campoInicial, Nullable<int> largoCampo)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            var idArchivoParameter = idArchivo.HasValue ?
                new ObjectParameter("IdArchivo", idArchivo) :
                new ObjectParameter("IdArchivo", typeof(int));
    
            var numeroLineaParameter = numeroLinea.HasValue ?
                new ObjectParameter("NumeroLinea", numeroLinea) :
                new ObjectParameter("NumeroLinea", typeof(int));
    
            var campoInicialParameter = campoInicial.HasValue ?
                new ObjectParameter("CampoInicial", campoInicial) :
                new ObjectParameter("CampoInicial", typeof(int));
    
            var largoCampoParameter = largoCampo.HasValue ?
                new ObjectParameter("LargoCampo", largoCampo) :
                new ObjectParameter("LargoCampo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_SumaDetalleEnTotal", valorParameter, idArchivoParameter, numeroLineaParameter, campoInicialParameter, largoCampoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pa_valida_TotalNominaEnLiquidacion(string valor, Nullable<int> idArchivo, Nullable<int> numeroLinea, Nullable<int> campoInicial, Nullable<int> largoCampo)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            var idArchivoParameter = idArchivo.HasValue ?
                new ObjectParameter("IdArchivo", idArchivo) :
                new ObjectParameter("IdArchivo", typeof(int));
    
            var numeroLineaParameter = numeroLinea.HasValue ?
                new ObjectParameter("NumeroLinea", numeroLinea) :
                new ObjectParameter("NumeroLinea", typeof(int));
    
            var campoInicialParameter = campoInicial.HasValue ?
                new ObjectParameter("CampoInicial", campoInicial) :
                new ObjectParameter("CampoInicial", typeof(int));
    
            var largoCampoParameter = largoCampo.HasValue ?
                new ObjectParameter("LargoCampo", largoCampo) :
                new ObjectParameter("LargoCampo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pa_valida_TotalNominaEnLiquidacion", valorParameter, idArchivoParameter, numeroLineaParameter, campoInicialParameter, largoCampoParameter);
        }
    }
}
