//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MontoAlto
    {
        public int MontoAltoId { get; set; }
        public string TipoParametro { get; set; }
        public string Correo { get; set; }
        public int Valor { get; set; }
        public string Observacion { get; set; }
    }
}
