//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int PagoId { get; set; }
        public int ArchivoId { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaPago { get; set; }
        public int Estado { get; set; }
        public int SiniestroId { get; set; }
        public decimal Monto { get; set; }
        public decimal PagoVC { get; set; }
        public System.DateTime FechaTransferencia { get; set; }
        public int MonedaId { get; set; }
        public int NominaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<bool> Vigente { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Siniestro Siniestro { get; set; }
    }
}
