//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int ParametroId { get; set; }
        public int TipoMovimientoId { get; set; }
        public int TipoSolicitudId { get; set; }
        public int TipoOperacion { get; set; }
        public string CentroCosto { get; set; }
        public string CuentaContable { get; set; }
        public string SignoCuenta { get; set; }
        public bool Vigente { get; set; }
    }
}
