//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parentesco
    {
        public int ParentescoId { get; set; }
        public string DescripcionParentesco { get; set; }
        public string CodBeneficiario { get; set; }
        public int PorcentajeBeneficiario { get; set; }
    }
}
