//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoInforme
    {
        public TipoInforme()
        {
            this.TipoArchivoes = new HashSet<TipoArchivo>();
        }
    
        public int TipoInformeId { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<TipoArchivo> TipoArchivoes { get; set; }
    }
}
