//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    
    public partial class pa_file_ObtieneErrorArchivo_Result
    {
        public string NombreArchivo { get; set; }
        public string TipoLinea { get; set; }
        public Nullable<int> NumeroLinea { get; set; }
        public Nullable<int> CampoInicial { get; set; }
        public Nullable<int> LargoCampo { get; set; }
        public string ValorCampo { get; set; }
        public string InformacionCampo { get; set; }
        public string FormatoContenido { get; set; }
    }
}
