//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    
    public partial class pa_impactanegocio_Result
    {
        public Nullable<int> Linea { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<int> ContratoId { get; set; }
        public Nullable<int> TipoMovimientoId { get; set; }
        public Nullable<int> AfpId { get; set; }
        public string Cuspp { get; set; }
        public Nullable<int> SolicitudId { get; set; }
        public Nullable<int> Monedaid { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Pago { get; set; }
        public string usuariomodificacion { get; set; }
        public string CodTransferencia { get; set; }
    }
}
